name: widget_and_text_animator
description: Make animating widgets a breeze with much less code and many effects built in. In addition, make Text animations beautiful with staggered text effects. transitions, blurs & more.
version: 1.0.6
homepage: https://github.com/andrewpmoore/widget_and_text_animator

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  lints: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


