# Steps to take before publishing
#
# change pubspec.yaml version
# change changelog.md
# change line 13 readme.md
# dart format .
# dart pub publish --dry-run
# dart pub publish


name: widget_and_text_animator
description: Make animating widgets a breeze with many effects built in. Make Text animations beautiful with staggered text effects. transitions, blurs & more, animate gestures too
version: 1.1.2
homepage: https://github.com/andrewpmoore/widget_and_text_animator

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  lints: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


screenshots:
  - description: 'WidgetAnimator sample'
    path: wave.gif
  - description: 'TextAnimator sample'
    path: text_sample.gif
  - description: 'Widget sequence sample'
    path: widget_sequence.gif