library widget_and_text_animator;

export 'src/widget_animator.dart';
export 'src/widget_animator_sequence.dart';
export 'src/text_animator.dart';
export 'src/styles/animation_settings.dart';
export 'src/styles/animation_style.dart';
export 'src/styles/atRest/animation_style_bounce.dart';
export 'src/styles/animation_style_builder.dart';
export 'src/styles/atRest/animation_style_dangle.dart';
export 'src/styles/atRest/animation_style_fidget.dart';
export 'src/styles/atRest/animation_style_none.dart';
export 'src/styles/atRest/animation_style_pulse.dart';
export 'src/styles/atRest/animation_style_rotate.dart';
export 'src/styles/atRest/animation_style_size.dart';
export 'src/styles/atRest/animation_style_slide.dart';
export 'src/styles/atRest/animation_style_swing.dart';
export 'src/styles/atRest/animation_style_vibrate.dart';
export 'src/styles/atRest/animation_style_wave.dart';
